services:
  #Banco de daods PostgreSQL
  postgres:
    image: postgres:16.7
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${POSTGRES_TZ}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
      
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
      - pgdata:/var/lib/postgresql/data:Z
      - ./init_script:/docker-entrypoint-initdb.d:Z

      
  #Sistema de backup
  #backup:
  #  image: alpine
  #  volumes:
  #    - pgdata:/backup
  #  command: ["sh", "-c", "tar czf /backup/pgdata.tar.gz /backup"]

      
  #keycloack - IAM - Gerenciador de acesso
  keycloak:
    image: quay.io/keycloak/keycloak:26.4.6
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:${POSTGRES_PORT}/${KEYCLOAK_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/realms:/opt/keycloak/data/import:Z
    command: [ "start-dev", "--import-realm" ]      
      

volumes:
  pgdata:
  
